### PR TITLE
Fix Blazorise.Bootstrap version

### PR DESCRIPTION
**Pull request by do-it-ger**
Volo.Abp.BlazoriseUI =>  PackageReference Include="Blazorise.Bootstrap" Version="0.9.3-preview2" />

### CODE REVIEW

**Comment by maliming** [comment]
Hi

We will upgrade all samples recently.

You can test it again.

**Comment by stsrki** [comment]
@do-it-ger Why did you downgrade from preview3 to preview2?

**Comment by do-it-ger** [comment]
@stsrki  no version preview3 on nuget.org found - project could not compiled
The basic theme reference preview2
image

**Comment by stsrki** [comment]
@do-it-ger It's probably because it's missing a NuGet.config from the solution or project folder. Look at this https://github.com/abpframework/abp/blob/dev/NuGet.Config

**Comment by do-it-ger** [comment]
@stsrki yes the   <add key="BlazoriseMyGet" value="https://www.myget.org/F/blazorise/api/v3/index.json" /> is missing in the solution. That's the problem. Not found on nuget.org:

Acme.BookStore.Blazor\Acme.BookStore.Blazor.csproj : error NU1102: Unable to find package Blazorise.Bootstrap with version (>= 0.9.3-preview3)

Maybe it's better to include the Blazorise.Bootstrap / fontawesome into an separate Volo.Blazorise.Bootstrap project and include the Volo.Abp.BlazoriseUi. Currently you have to update the version in 2 projects.

**Comment by do-it-ger** [comment]
@stsrki i cole the the issue it was my NuGet.config

**Pull request closed without merging**
