### PR TITLE
Update `BookStore-Mvc-EfCore` to 8.0.0.

### PR DESCRIPTION
**Pull request by maliming**

### CODE REVIEW

**Comment by GreatGuard** [comment]
Acme.BookStore.Application.Tests
Unit tests are not recognized right now.

**Comment by GreatGuard** [comment]
Acme.BookStore.Application.Tests
cann't find any unit test
image

**Comment by maliming** [comment]
hi

The implementation of unit test methods exists on EF Core.

**Comment by GreatGuard** [comment]
ok,ths

**Pull request merged**
